name: Build Qt Conan Recipe
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: Windows32Bit,
            os: windows-latest,
            conan-libcxx-setting: -s compiler.libcxx=libstdc++11,
            conan-arch-settings: --settings arch=x86
          }
        - {
            name: Windows64Bit,
            os: windows-latest,
            conan-libcxx-setting: -s compiler.libcxx=libstdc++11,
            conan-arch-settings: ""
          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.x
      - name: download or build package
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user conan
          conan user
          conan install --build=missing ${{ matrix.config.conan-arch-settings }} qt/5.15.2@
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: "C:/Users/runneradmin/.conan/data/qt/5.15.2/_/_/package/"
          name: ${{ matrix.config.name }}
