name: Build Qt Conan Recipe
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on:  windows-latest
    strategy:
      matrix:
        arch: [x86, x86_64]
        qt-version: [5.15.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.x
      - name: Download or build Qt Package
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user conan
          conan user
          conan install --build=missing --settings arch=${{ matrix.arch }} -o qt:shared=True qt/${{ matrix.qt-version }}@
          mkdir artifacts
          xcopy $(cat C:\Users\runneradmin\.conan\data\qt\${{ matrix.qt-version }}\_\_\package\**\.conan_link) .\artifacts\ /E /Y
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts
          name: Qt-${{ matrix.qt-version }}-Win-${{ matrix.qt-version }}
