name: Build Qt Conan Recipe
on: [push, pull_request]

jobs:
  build:
    name: Qt ${{ matrix.qt-version }} Windows ${{ matrix.arch }}
    runs-on:  windows-latest
    strategy:
      matrix:
        arch: [x86]
        qt-version: [5.15.1@] # , 5.12.5@bincrafters/stable, 6.0.1@bincrafters/stable]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
         python-version: 3.x
      - name: Download or build Qt Package
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user conan
          conan user
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan install --build=missing --settings arch=${{ matrix.arch }} conan-libiconv-excerpt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts
          name: Qt-${{ env.QTVERS }}-Win-${{ matrix.arch }}
