name: Build Qt Conan Recipe
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: Windows-32Bit,
            os: windows-latest,
            conan-libcxx-setting: -s compiler.libcxx=libstdc++11,
            conan-arch-settings: --settings arch=x86
          }
        - {
            name: Windows-64Bit,
            os: windows-latest,
            conan-libcxx-setting: -s compiler.libcxx=libstdc++11,
            conan-arch-settings: ""
          }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
         python-version: 3.x
      - name: Download or build Qt Package
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user conan
          conan user
          conan install --build=missing ${{ matrix.config.conan-arch-settings }} -o qt:shared=True qt/5.15.2@
          mkdir artifacts
          xcopy $(cat ..\..\.conan\data\qt\5.15.2\_\_\package\**\.conan_link) .\artifacts\ /E /Y
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: artifacts
          name: ${{ matrix.config.name }}
